---
title: "backfire-minimal-1"
author: "mht"
date: "January 23, 2016"
output: html_document
---


```{r}
library(data.table)
library(coda)
estimate_mode <- function(s) {
  d <- density(s)
  return(d$x[which.max(d$y)])
}
HPDhi<- function(s){
  m <- HPDinterval(mcmc(s))
  return(m["var1","upper"])
}
HPDlo<- function(s){
  m <- HPDinterval(mcmc(s))
  return(m["var1","lower"])
}
options("scipen"=10)   
```


```{r}
d1<-read.csv("/Users/mht/Documents/research/backfiring-words/mturk/minimal-1/round1/minimal-1-trials.csv")
d2<-read.csv("/Users/mht/Documents/research/backfiring-words/mturk/minimal-1/round2/minimal-1-trials.csv")

d<- bind_rows(d1, d2)

roundToBin <- function(x){
  y <- if (x < 0.05){
    0.01
  } else if (x > 0.95) {
    0.99
  } else {
   round(x,1)
  }
  return(y)
}


d<-d %>% 
  mutate(rounded_logfreq = round(logfreq*2)/2) %>% 
  mutate(normed_logval = logfreq/log(365*5)) %>%
  mutate(normed_logval = ifelse(normed_logval > 0.999, 0.999, normed_logval)) %>%
  rowwise() %>%
  mutate(rounded_normed_logfreq = roundToBin(normed_logval)) %>%
  ungroup()


#write.csv(d, "~/Documents/research/backfiring-words/models/data/minimal-1-pilot.csv", row.names = F)



table(d$condition)/27
```

```{r}

d<-read.csv("/Users/mht/Documents/research/backfiring-words/data/minimal-1-trials.csv")

c<-read.csv("/Users/mht/Documents/research/backfiring-words/data/minimal-1-catch_trials.csv")

with(c %>% filter(pass==0), table(condition, response))
  with(c %>% filter(pass==1), table(condition))

d <- left_join(d,c %>% select(workerid, pass)) %>% 
  filter(pass==1) %>%
  mutate(daily_prob = freq_5years / (365*5))



ggplot(d, aes(x = logfreq, fill=condition))+
  geom_histogram(position=position_dodge())+
  facet_wrap(~item)

```

Most preferrred time window

```{r}
d.windows<-d %>% 
  group_by(item) %>%
  summarize(pref_window=names(table(timeWindow))[which.max(table(timeWindow))])
  

d<-left_join(d, d.windows)


adjustTo5Years = list(
  week = 5*52,
  month = 5*12,
  year = 5,
  "5 years" = 1
)


d0<-d %>% 
  rowwise() %>% 
  mutate(ntimes_prefwindow = ifelse(timeWindow == pref_window, 
                 n_times, 
                 n_times*adjustTo5Years[[as.character(timeWindow)]]/
                   (adjustTo5Years[[as.character(pref_window)]]))) %>%
  mutate(rounded_ntimes_prefwindow = round(ntimes_prefwindow))

d0<- d0[complete.cases(d0),]

#write.csv(d0, "~/Documents/research/backfiring-words/models/data/minimal-1-prefwindow.csv", row.names = F)

View(d0 %>% select(n_times, timeWindow, ntimes_prefwindow, pref_window,rounded_ntimes_prefwindow))
```

```{r}
d.cigs <- d %>% 
  filter(item == "smokes cigarettes") %>%
  select(condition, timeWindow,n_times, logfreq)

d.socks <- d %>% 
  filter(item == "wears socks") %>%
  select(condition, timeWindow,n_times, logfreq)
View(d.socks)
```


```{r}

d %>% group_by(condition) %>% summarize(n = length(logfreq)/27)



d.item.stat <- d %>% 
  group_by(item, condition) %>%
  #multi_boot_standard(column="logfreq")
  multi_boot_standard(column="daily_prob")



ggplot(d.item.stat, aes(x = condition, y = mean, 
                        ymin = ci_lower, ymax= ci_upper, 
                        fill=condition))+
  geom_bar(stat='identity', position=position_dodge(), color = 'black')+
  geom_errorbar(position=position_dodge())+
  facet_wrap(~item, scales='free')+
  ylab("n times / day")+
  theme(axis.text.x = element_blank())

ggsave("~/Documents/research/backfiring-words/analysis/figures/minimal-1.pdf", width = 18, height = 9)
```


```{r}
d.obs.comm<- left_join(
            left_join(d.item.stat  %>%
                     filter(condition=='observation') %>%
                     rename(obs_mean = mean,
                            obs_ci_lower = ci_lower,
                            obs_ci_upper = ci_upper) %>%
                       ungroup() %>%
                       select(-condition),
                   d.item.stat %>%
                     filter(condition=='communication') %>%
                     rename(com_mean = mean,
                            com_ci_lower = ci_lower,
                            com_ci_upper = ci_upper) %>%
                     ungroup() %>%
                       select(-condition)),
            d.item.stat  %>%
                     filter(condition=='baseline') %>%
                     rename(base_mean = mean,
                            base_ci_lower = ci_lower,
                            base_ci_upper = ci_upper) %>%
                       ungroup() %>%
                       select(-condition))
            


ggplot(d.obs.comm, aes(x=obs_mean, xmin = obs_ci_lower, xmax = obs_ci_upper,
                       y = com_mean, ymin = com_ci_lower, ymax = com_ci_upper,
                       color=base_mean))+
  geom_point(size = 3)+
  geom_errorbar()+
  geom_errorbarh()+
  geom_abline(intercept = 0, slope = 1, lty = 3)+
  coord_fixed()+
  xlim(0,9.5)+
  ylim(0,9.5)

ggsave("~/Documents/research/backfiring-words/analysis/figures/minimal-1-log-comVsObs.pdf")


ggplot(d.obs.comm, aes(x=base_mean, xmin = base_ci_lower, xmax = base_ci_upper,
                       y = com_mean, ymin = com_ci_lower, ymax = com_ci_upper))+
  geom_point(size = 3)+
  geom_errorbar()+
  geom_errorbarh()+
  geom_abline(intercept = 0, slope = 1, lty = 3)+
  coord_fixed()+
 xlim(-0.5,9.5)+
  ylim(-0.5,9.5)

ggsave("~/Documents/research/backfiring-words/analysis/figures/minimal-1-log-comVsbase.pdf")



ggplot(d.obs.comm, aes(x=base_mean, xmin = base_ci_lower, xmax = base_ci_upper,
                       y = obs_mean, ymin = obs_ci_lower, ymax = obs_ci_upper))+
  geom_point(size = 3)+
  geom_errorbar()+
  geom_errorbarh()+
  geom_abline(intercept = 0, slope = 1, lty = 3)+
  coord_fixed()+
 xlim(-0.5,9.5)+
  ylim(-0.5,9.5)

ggsave("~/Documents/research/backfiring-words/analysis/figures/minimal-1-log-obsVsbase.pdf")


```


### Using normed log frequency (max val = 1)

```{r}
d.item.day.stat <- d %>% 
  group_by(item, condition) %>%
  #multi_boot_standard(column="normed_logval") %>%
  multi_boot_standard(column="rounded_normed_logfreq")



ggplot(d.item.day.stat, aes(x = condition, y = mean, 
                        ymin = ci_lower, ymax= ci_upper, 
                        fill=condition))+
  geom_bar(stat='identity', position=position_dodge(), color = 'black')+
  geom_errorbar(position=position_dodge())+
  facet_wrap(~item)+
  ylab("Log frequency")+
  theme(axis.text.x = element_blank())

```



```{r}
d.item.day.stat<-d.item.stat
d.obs.comm<- left_join(
            left_join(d.item.day.stat  %>%
                     filter(condition=='observation') %>%
                     rename(obs_mean = mean,
                            obs_ci_lower = ci_lower,
                            obs_ci_upper = ci_upper) %>%
                       ungroup() %>%
                       select(-condition),
                   d.item.day.stat %>%
                     filter(condition=='communication') %>%
                     rename(com_mean = mean,
                            com_ci_lower = ci_lower,
                            com_ci_upper = ci_upper) %>%
                     ungroup() %>%
                       select(-condition)),
            d.item.day.stat  %>%
                     filter(condition=='baseline') %>%
                     rename(base_mean = mean,
                            base_ci_lower = ci_lower,
                            base_ci_upper = ci_upper) %>%
                       ungroup() %>%
                       select(-condition))
            


ggplot(d.obs.comm, aes(x=obs_mean, xmin = obs_ci_lower, xmax = obs_ci_upper,
                       y = com_mean, ymin = com_ci_lower, ymax = com_ci_upper,
                       color=base_mean))+
  geom_point(size = 3)+
  geom_errorbar()+
  geom_errorbarh()+
  geom_abline(intercept = 0, slope = 1, lty = 3)+
  coord_fixed()+
  xlim(-0.05,2)+
  ylim(-0.05,2)

ggsave("~/Documents/research/backfiring-words/analysis/figures/minimal-1-dayrate-noSmoking-comVsObs.pdf")


ggplot(d.obs.comm, aes(x=base_mean, xmin = base_ci_lower, xmax = base_ci_upper,
                       y = com_mean, ymin = com_ci_lower, ymax = com_ci_upper))+
  geom_point(size = 3)+
  geom_errorbar()+
  geom_errorbarh()+
  geom_abline(intercept = 0, slope = 1, lty = 3)+
  coord_fixed()+
  xlim(-0.05,1.5)+
  ylim(-0.05,1.5)


ggsave("~/Documents/research/backfiring-words/analysis/figures/minimal-1-dayrate-noSmoking-comVsbase.pdf")



ggplot(d.obs.comm, aes(x=base_mean, xmin = base_ci_lower, xmax = base_ci_upper,
                       y = obs_mean, ymin = obs_ci_lower, ymax = obs_ci_upper))+
  geom_point(size = 3)+
  geom_errorbar()+
  geom_errorbarh()+
  geom_abline(intercept = 0, slope = 1, lty = 3)+
  coord_fixed()+
  xlim(-0.05,2)+
  ylim(-0.05,2)

ggsave("~/Documents/research/backfiring-words/analysis/figures/minimal-1-dayrate-noSmoking-obsVsbase.pdf")
```



# Model

```{r}

filePath <- "~/Documents/research/backfiring-words/models/results/"
prefix <-"bda-backfire-minimal-IncrMH"
#bda-backfire-minimal-IncrMH1k-b0.5k_priorMH10k-b5ka.csv
samples <- 50000
burn <- samples / 2
priorsamples <- 50000
priorburn <- priorsamples / 2
m.samples<- data.frame()
i = "b"
#for (i in c("a", "b")){
  m<-read.csv(paste(filePath, prefix, 
                     samples/1000, "k-b", 
                     burn/1000, "k_priorMH",
                     priorsamples/1000, "k-b",
                     priorburn/1000,
                     "k",i,".csv",sep=""))  
  m.samp <- m[rep(row.names(m), m$Probability*(samples-burn)), 1:4]
  m.samples<- bind_rows(m.samples, m.samp)
  print(i)
#}
m.params <- m.samples %>% filter(Type =='parameter')
m.pred <- m.samples %>% filter(Type == 'predictive_5yr')

```


```{r tj3.model.params}
qplot(data=m.params, x= Value, geom='histogram')+
  facet_wrap(~Condition, scales='free')

m.params %>%
  group_by(Condition) %>%
    summarise(MAP = estimate_mode(Value),
            credHigh = HPDhi(Value),
            credLow = HPDlo(Value)) 
```



```{r tj2.model.pred}

m.predStats <- m.pred %>%
  group_by(Condition, Item) %>%
  summarise(MAP = estimate_mode(Value),
            credHigh = HPDhi(Value),
            credLow = HPDlo(Value)) %>%
  rename(item = Item,
         condition = Condition) %>%
  ungroup() %>%
  filter(condition == "communication_plusGuess") %>%
  mutate(condition = factor(condition, labels=c("communication")))


d.daily <- d0 %>% group_by(condition, item) %>%
  multi_boot_standard(column = "daily_prob")
d.5year <- d0 %>% group_by(condition, item) %>%
  multi_boot_standard(column = "freq_5years")


# %>%
#   mutate(condition = factor(condition, 
#                             levels=c("baseline", "observation", "backfire"),
#                             labels=c("baseline", "observation", "communication")))

m.d<- left_join(m.predStats %>%
                  mutate(MAP = MAP / (365*5),
                         credLow = credLow / (365*5),
                         credHigh = credHigh / (365*5))
                  , d.daily)
m.d<- left_join(m.predStats, d.5year)

plt2<-ggplot(m.d,aes(x=MAP, y = mean, fill=condition))+
  geom_abline(intercept = 0, slope = 1, lty = 2)+
  geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper))+
  geom_errorbarh(aes(xmin=credLow, xmax = credHigh))+
    geom_point(shape=21, size=4)+
  xlim(-0.05,1.05)+
  ylim(-0.05,1.05)+
  theme_paper()+
 # coord_fixed()+
  xlab("\n Model posterior predictive")+
  ylab("Human \n")+
  theme(legend.title = element_text(hjust=0),
        legend.position="bottom",
        legend.direction="horizontal")+
  facet_wrap(~condition)

plt2

ggplot(m.d, aes(x=condition, y=MAP, ymin = credLow, ymax=credHigh, fill=condition))+
  geom_bar(stat='identity', position=position_dodge(), color = 'black')+
  facet_wrap(~item)+
  geom_errorbar(position=position_dodge())

# 
# plt2
# 
# +
#   guides(fill=F)
# 
# 
# plt2
# # 
# with(m.d, cor(MAP, mean))^2
# 
# with(m.d, cor(MAP, mean, use="complete.obs"))^2

# with(m.d %>% filter(logFreq >= 4.5),
#      cor(MAP,mean))^2
# 
# 
# plt4<-grid.arrange(plt1,plt3, plt2, nrow=1)
# # plt3<-arrangeGrob(plt1,plt2,nrow=1)
# # 
#  ggsave(file="~/Documents/research/habituals/writing/_cogsci2016/figures/tj-expt3-scatters.pdf", 
#         plot=plt3)#"talks/lab-mtg-120115/images/tj1-md-scatter-3colors.pdf")
# # 
# 
#  m.d <- m.d %>%
#    mutate(sqerr = (MAP-mean.x)^2)
#  View(m.d)
```

```{r}


m.obs.comm<- left_join(
            left_join(m.predStats  %>%
                     filter(condition=='observation') %>%
                     rename(obs_mean = MAP,
                            obs_ci_lower = credLow,
                            obs_ci_upper = credHigh) %>%
                       ungroup() %>%
                       select(-condition),
                   m.predStats  %>%
                     filter(condition=='communication') %>%
                     rename(com_mean = MAP,
                            com_ci_lower = credLow,
                            com_ci_upper = credHigh) %>%
                     ungroup() %>%
                       select(-condition)),
            m.predStats  %>%
                     filter(condition=='baseline') %>%
                     rename(base_mean = MAP,
                            base_ci_lower = credLow,
                            base_ci_upper = credHigh) %>%
                       ungroup() %>%
                       select(-condition))
            

ggplot(m.obs.comm, aes(x=obs_mean, xmin = obs_ci_lower, xmax = obs_ci_upper,
                       y = com_mean, ymin = com_ci_lower, ymax = com_ci_upper,
                       color=base_mean))+
  geom_point(size = 3)+
  geom_errorbar()+
  geom_errorbarh()+
  geom_abline(intercept = 0, slope = 1, lty = 3)+
  coord_fixed()+
  xlim(-0.05,1.05)+
  ylim(-0.05,1.05)

with(m.obs.comm, cor(obs_mean, com_mean))

```